# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_description', models.CharField(blank=True, max_length=120, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField()),
            ],
            options={
                'ordering': ['-priority', 'pub_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_pass', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaulttodo.User'),
        ),
    ]
