# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaulttodo', '0004_auto_20180327_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
