# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0002_auto_20180402_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_advance',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
